spring:
  datasource:
    url: ${CODERINTUITION_DATASOURCE_URL}
    username: ${CODERINTUITION_DATASOURCE_USERNAME}
    password: ${CODERINTUITION_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CODERINTUITION_GOOGLE_CLIENT_ID}
            clientSecret: ${CODERINTUITION_GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: ${CODERINTUITION_JWT_SECRET}
    tokenExpirationMs: 604800000
  oauth2:
    authorizedRedirectUris:
      - https://coderintuition.com/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
server:
  forward-headers-strategy: framework
